### ISSUE TITLE
Still do not know how to use it

### ISSUE THREAD

**Issue by link-ding** [hannesfrank/remnote-schedule#1]
I follow the all things in the readme and add the plugin in the RemNote but it does not work for me.

![](https://cdn.discordapp.com/attachments/719288461231652984/747970648323784794/unknown.png)

can you make some video to show how to use it? Thanks in advance!!!

**Comment by hannesfrank** [comment]
Thanks for the report! I made a few mistakes in the build process.

This is fixed in 368c86a80a91651249078403fd6653fdf5890eb1.
