### ISSUE TITLE
Showing past events

### ISSUE THREAD

**Issue by richardlm** [hannesfrank/remnote-schedule#11]
Hi. As far as I can see, this ignores any event that is scheduled before the current system time - is that correct?
If so, do you plan to add functionality to show **all** events on a day?
Thanks.

**Comment by hannesfrank** [comment]
The red line shows the current time and it should definitely be possible to have events before it. Can you show me a screenshot of an example where this does not happen?

There is also a setting to define the rendered schedule interval (by default 6am to 10pm): https://github.com/hannesfrank/remnote-schedule#start-and-end-time

**Comment by richardlm** [comment]
Having experimented with my entries it looks like the reason it wasn't working properly was because I set my calendar start to 0000 and end to 2400. I changed the start time to 0100 and it now allows entries at any time of the day.

The reason I set 0000 and 2400 was to give a 24-hour calendar, but it is not that important.

There is still one oddity that baffles me: I have one daily document (15th January 2021) on which the schedule refuses to show anything. I have completely deleted all schedule-related rems from that day and added them back in - exactly as on other daily pages - but the schedule will not show them! I don't know how to troubleshoot beyond that unfortunately. Is it worth opening another issue for that?
Thanks.

**Comment by hannesfrank** [comment]
Sorry, I can not reproduce your problem. It shows like that:

![image](https://user-images.githubusercontent.com/4137110/105039441-dca39380-5a60-11eb-8d00-a417510fd5c9.png)

using that plugin URL:

```
https://hannesfrank.github.io/remnote-schedule/index.html?start-time=0&end-time=2400
```

Your 15th January problem sounds quite strange as well. Maybe you can press F12 and look in teh DevTools console for an error. The error handling of that plugin could definitely be improved.

**Comment by richardlm** [comment]
Hi Hannes - solved the 15th January issue!
I was using the same page to learn about RemNote, including templates. I want to insert the visual schedule as part of my daily template so I had rems relating to that lower down the page as I was testing it.
I copied everything on the page (except the template testing rems), deleted the page, created another 15th January daily page, pasted everything in - and it worked.
Many thanks.
