### ISSUE TITLE
Chart Renders but Entries Do Not

### ISSUE THREAD

**Issue by lswank** [hannesfrank/remnote-schedule#18]
Hi! If I understand the installation instructions properly, once you have this installed it will render anything in the correct format that is listed underneath a node named "Schedule".

Mine does not appear to be doing that thing. 

<img width="600" alt="Screen Shot 2021-10-11 at 4 17 00 PM" src="https://user-images.githubusercontent.com/999530/136862069-10f4b5f3-8a5d-4993-8a9d-9ef9844cc323.png">

**Comment by hannesfrank** [comment]
Try another `,` after the second time part.
![image](https://user-images.githubusercontent.com/4137110/137207200-e224e77b-c0b1-4d10-be4c-60c508309562.png)



I guess one could extend the regex pattern and allow any whitespace instead or in combination with the `,`.

**Comment by lswank** [comment]
Beautiful! That did it. You are the hero of RemNote plugins. We should discuss collaborating on a port of https://roamjs.com/extensions/discourse-graph to RemNote. I think it would pull a lot of serious PhD students and researchers over from Roam.
